language: python
sudo: required
dist: xenial
python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install .
script: pytest
deploy:
  provider: pypi
  user:
    secure: JT7b8ZTL6yRGWyFoJtP5IEOXjq4nphsryRjYjQVi+XtPLIwbvlX2ZdnH0H7k7EFR8mYUaIyRuGAnuoMOwiscC91m7qukvuOgFSAKsUcuJR7aTTbDZdWM/WutU8Zk9pC5vFzduL2eIYYTufwvFlJxqLzyMI6ebQH7izwfMLSVfaYwm4u7Ob1qa7XMqcwxx4ga2o4Z50QXJKFOnc7LaYpQWAv8rTqgxAvCjQQlSr8GRm1SHntMIWiDW3KOUuoe0G+0/HjZgeqZWVnf8tipGd1eHpn2vNvozvBFSo2upPyvbqKWk+XU4tBCPrrP592UTfF9gqL0MpATzCQ4TUimAl2Cr8+zuYGPmzl32uuROX/3U4lg9jJXFXE8IY1lPG4tLxr2Gkc1RrTBSFoL+9faqHleAxepxLBhceR6fV1g1PSb8O8+gGVt8g8SpZCz/zsfbV+i9ukL+fjlQHK6hOLZRJY4ixSy7XTl+sxuApc4/au9Z8kt39cIFe6zlqLz+1gLbwXIf2fQ9nHPYFE0P/nG03sbflmdL2zxH9jumBF1jJjSQXrKRcpknyOvG5RLAO95tFpAO8Ovn92twjd82ugPHlPCYEeOtxYorWDvgoQn00f/roIdXi0bdEccu05zdguJiUu6ziwheLVvoMsXHfaW0+tzwWLhB2fI3lxhEsRaht3IqLw=
  distributions: sdist bdist_wheel
  password:
    secure: GvwBNstKo72h9wNMIls0LarQFYF7nITH/S/YPAviKNOUW7k0PfwFMplOm3d6+ZHU1MhXGyea1O4Xg1CzjWQLVIlIIQOJnq230OSjeYXIKEbKIaSSjjhlAo4dl5XEX+tU6GaJSU23HjTfQbHrsrYOB16W00yO238YNikrUqA2ojOMDwpEb0OpzfvR6ah4ILuw7mg7+mOTGKqM7oqiPG8AE558DqDa+NibUZLWzk/HyUnYx8seVM184FETmTftvovsBgNt3yP14955lUzodrDyB1J/Osi5EVNpF3k/C3rvr9djL0jbgoxi+4KhvZGC+29xn296Iw3LxxbCKFunDqIb1tl4NcS/fxB2Ycl490Q9JhQhIaMDD724cJkgxTXm4Qqzl5mVW0ZRIy/zjwQRvkrOJj5+GbvbdMn6a41w2YHkKeTElOh7MEVAxM3omwD92P4GAsHzIGYlNtbuhaem8dGXcZsTL9MgxhTnJYQGJlCVX8PlbCmNVOlKpGCJJ3bgsicR2jdjEM8ApDFFYO0V4sTphAXDf+6OCgZK09a/nrCj4vRYAG05VbbPN4s3QCcerzGlM9WPbygA0C/gHLBCx5sPpgkGiWNZ0zdbI6DG0o5jkHm1UMZKoXYrAU4HgTeTygHtYwcYLjK+rlcXI20EvNu2WesDdfpfUiCdJJZRT48Oae4=
  on:
    tags: true
